<?php
/**
 *    OpenSource-SocialNetwork
 * Traduzido por: Wallenberg Andrade
 * WhatsApp:  +55(83)8169-5837
 * Email:     wallenandrade@gmail.com
 * @package   (Informatikon.com).ossn
 * @author    OSSN Core Team <info@opensource-socialnetwork.com>
 * @copyright 2014 iNFORMATIKON TECHNOLOGIES
 * @license   General Public Licence http://opensource-socialnetwork.com/licence
 * @link      http://www.opensource-socialnetwork.com/licence
 */

$pt = array(
	'home' => 'Inicio',
	'site:index' => 'Bem Vindo!',
	'news:feed' => 'Notícias',
	'new:feed' => 'Notícias',
	'photos:ossn' => 'Fotos',
	'admin:view:site' => 'Visão geral',

	'home:top:heading' => "Bem Vindo a Rede Social da %s! Cadastre-se agora para conversar com seus amigos e professores, criar grupos, adicionar fotos e muito mais.",
	'create:account' => 'Crie sua conta agora',
	'its:free' => "Divirta-se nas horas vagas.",

	'register:ok:message' => "Parabéns! Sua conta foi criada. Um e-mail de ativação foi enviado para sua caixa postal. Se você não receber o e-mail , por favor, verifique a pasta de spam.",

	'copyright' => '&copy; COPYRIGHT',
	'powered' => 'Distribuído por Open Source Social Network. | Traduzido por: Wallenberg Andrade',

	'name' => 'Nome',
	'birthdate' => 'Data de nascimento',
	'first:name' => 'Primeiro Nome',
	'last:name' => 'Sobre Nome',
	'email' => 'Email',
	'email:again' => 'Confirmar Email',
	'username' => 'Nome do Usuário',
	'password' => 'Senha',
	'day' => 'Dia',
	'month' => 'Mês',
	'year' => 'Ano',
	'male' => 'Masculino',
	'female' => 'Feminino',
	'account:create:notice' => 'Ao clicar em Criar uma conta , você concorda com a nossa Política de Privacidade',
	'gender' => 'Gênero',

	'acount:settings' => 'Configurações da conta',
	'page:error' => 'Página não encontrada!',
	'page:error:text' => 'A página solicitada não está disponível ou podem ter sido excluídos.',
	'page:error:heading' => '404',

	'search:users' => 'Pessoas',
	'admin:logout' => 'Deslogar',
	'admin:menu' => 'Administrador',
	'feedback' => 'Enviar comentários',
	'logout' => 'Deslogar - Sair',

	'ossn:like:this' => '%s Gostou disso',
	'ossn:like:you:and:this' => 'Você e %s Gostou disso',
	'ossn:like:people' => '%s Pessoas',
	'ossn:like:person' => '%s Pessoa',
	'ossn:liked:you' => 'Você gostou disso',
	'ossn:unlike' => 'Descurtir',
	'ossn:like' => 'Curtir',

	'admin:components' => 'Componentes',
	'admin:dashboard' => 'Painel',
	'admin:install' => 'Instalador',
	'admin:themes' => 'Temas',
	'admin:basic' => 'Básico',
	'admin:cache' => 'Cache',
	'admin:mode' => 'Modo',
	'configure' => 'Configuração',
	'admin:help' => 'Ajuda',
	'admin:support' => 'Suporte',

	'ossn:update:check:error' => 'Error',

	'upload' => 'Upload',
	'save' => 'Salvar',
	'add' => 'Adicionar',
	'edit' => 'Editar',
	'search' => 'Buscar',
	'delete' => 'Excluir',

	'admin:users' => 'Lista de usuários',
	'admin:add:user' => 'Adicionar usuário',
	'admin:user:deleted' => 'O usuário foi excluído !',
	'admin:user:delete:error' => 'Não foi possível excluir o usuário! Por favor, tente novamente mais tarde.',

	'type' => 'Tipo',
	'normal' => 'Normal',
	'admin' => 'Administrador',

	'lastlogin' => 'Último Acesso',

	'my:version' => 'Versão da Rede: Estação Criança 1.0 - Open Source Social Network',
	'online:users' => 'Usuários Online !',
	'themes' => 'Temas',
	'users' => 'Usuários',
	'components' => 'Componentes',
	'available:updates' => 'Atualizações disponíveis',
	'website:name' => 'Nome do site web',
	'owner:email' => 'Email do administrador',
	'default:lang' => 'Idioma padrão',

	'timeline' => 'Linha do Tempo',
	'photos' => 'Fotos',
	'friends' => 'Amigos',
	'links' => 'Links',
	'ossn:add:user:mail:subject' => "%s por favor confirme seu endereço de correio eletrônico para %s!",
	'ossn:add:user:mail:body' => "Antes que possa começar a utilizar %s, deve confirmar seu endereço de correio eletrônico.

Confirme seu endereço de correio eletrônico, clicando no seguinte link:

%s

Se preferir, copie e cole o link em seu navegador, manualmente.

%s",
	'user:friends' => 'Amigos',
	'user:account:validated' => 'Sua conta foi verificada com êxito!',
	'user:account:validate:fail' => 'Não foi possível verificar a conta! Por favor, tente novamente mais tarde.',

	'cache:enabled' => 'Cache ativado com êxito!',
	'cache:disabled' => 'Cache desativado corretamente!',
	'cache:enable' => 'Habilitar cache',
	'cache:disable' => 'Desativar cache',

	'cache:1' => 'Ativado',
	'cache:0' => 'Desativado',
	'cache:notice' => 'Cache armazenará CSS e JS de arquivo, para ajudar no carregamento do site.',

	'theme:install:notice' => 'Faça o upload de arquivo .zip válido, com o tema',
	'com:install:notice' => 'Faça o upload de arquivo .zip válido, com pacote de componentes.',

	'login:error' => 'Usuário ou senha inválidos!',
	'login:error:sub' => "Não foi possível fazer o login. Por favor verifique seu nome de usuário e a senha.",
	'login:success' => 'Login efetuado com sucesso!',
	'com:installed' => 'Componente instalado com sucesso!',
	'com:install:error' => 'Não é possível instalar o componente! Certifique-se de que é um pacote válido.',
	'settings:saved' => 'Configuração salva',
	'com:deleted' => 'O componente foi excluído!',
	'com:delete:error' => 'Não é possível excluir o componente! Por favor, tente novamente mais tarde.',
	'com:disabled' => 'Desabilitado com êxito!',
	'com:enabled' => 'Componente Ativado!',


	'theme:delete:active' => 'Não é possível excluir tema ativo.',
	'theme:deleted' => 'O tema foi excluído.',
	'theme:delete:error' => 'Não é possível excluir o tema! Por favor, tente novamente mais tarde.',
	'theme:enabled' => 'Ativado com êxito!',
	'theme:installed' => 'Tema já instalado!',
	'theme:install:error' => 'Não é possível instalar o tema! Certifique-se de que trata-se de um tema válido.',

	'fields:require' => 'Todos os campos são obrigatórios!',
	'username:error' => 'Nome de usuário está incorreto.',
	'password:error' => 'A senha deve ter mais de 5 caracteres.',
	'account:created' => 'Sua conta foi criada, com sucesso.',
	'account:create:error:admin' => 'Não foi possível criar a conta! Por favor, tente novamente mais tarde.',
	'user:updated' => 'Usuário atualizado!',
	'logged:out' => 'Agora está desconectado!',
	'username:inuse' => 'Nome de usuário já existe! Por favor, selecione um nome de usuário diferente.',
	'email:inuse' => 'Endereço de correio eletrônico já existe! Por favor, tente outro endereço de correio eletrônico.',
	'email:invalid' => 'Endereço de correio eletrônico não é válido! Certifique-se de que o endereço de correio eletrônico foi digitado corretamente.',
	'email:error:matching' => "Endereço de correio eletrônico não coincide.",
	'account:created:email' => "Sua conta foi registrada! Enviamos para seu email, uma mensagem de ativação de conta. Se por acaso não recebê-la, por favor verifique sua caixa de SPAM",

	'administration' => 'Administração',

	'privacy' => 'Privacidade',
	'close' => 'Fechado',
	'open' => 'Abrir',
	'public' => 'Público',
	'friends' => 'Amigos',
	'privacy:public:note' => 'Todas as pessoas desse site podem ver isto.',
	'privacy:friends:note' => 'Somente seus amigos podem ver isto.',

	'add:friend' => 'Adicionar amigo',
	'cancel:request' => 'Cancelar solicitação',
	'remove:friend' => 'Eliminar',
	'no:friends' => 'Sem amigos',
	'settings' => 'Configuração',
	'ossn:add:friend:error' => 'Não é possível adicionar amigo!',
	'ossn:friend:request:submitted' => 'Sua solicitação de amizade foi enviada corretamente!',

	/* Upgrades */
	'upgrade:file:load:error' => 'Não é possível carregar o arquivo de atualização!',
	'upgrade:success' => "Seu site web foi atualizado com êxito  para versão %s.",
	'upgrade:failed' => "Não é possível atualizar o site para a versão %s.",
	'upgrade:not:available' => 'Não há nada para atualizar!',

	'site:login' => 'Entrar',

	/* Page errors */
	'system:error:title' => 'Algo deu errado!',
	'system:error:text' => 'Algo deu errado! Atualize esta página e tente novamente.',

	/* Password Reset */
	'reset:login' => 'redefinir senha',
	'reset:password' => 'redefinir sua  senha',
	'enter:new:password' => 'Insira sua nova senha abaixo e clique em ',
	'reset' => 'Redefinir',
	'enter:emai:reset:pwd' => 'Informe o endereço de correio eletrônico de sua conta, para redefinir sua senha.',
	'ossn:reset:password:subject' => 'Redefinir sua senha',
	'ossn:reset:password:body' => "Olá! %s,

Por favor, clique no link abaixo para redefinir a senha ou copie o link e cole na barra de endereços do seu navegador::

%s

%s",
	'passord:reset:success' => 'Senha redefinida com sucesso!',
	'passord:reset:fail' => 'Não é possível redefinir a senha! Por favor, tente novamente mais tarde.',
	'password:reset:email:required' => 'O endereço de correio eletrônico não pode estar vazio!',
	'passord:reset:email:success' => 'Instruções para reestabelecer a senha foram enviadas para o endereço de correio eletrônico informado.',
	'reset:password' => 'Redefinir a Senha',

	'erros:reporting' => 'Informe de erro',
	'erros:off' => 'Desativado',
	'erros:on' => 'Ativado',
	'basic:settings' => 'Ajustes Básicos',

	'ossn:new:version:error' => 'Desconhecido',
	'ossn:version:avaialbe' => "%s",

	'ossn:exception:title' => 'Ocorreu um erro de sistema. Por favor, tente novamente mais tarde. Você pode enviar um e-mail com os detalhes deste erro para o administrador do sistema em %s.',
	'ossn:securitytoken:failed' => 'A ação que você requisitou é inválida.',
	'ossn:component:delete:exception' => 'Você tem certeza que deseja deletar esse componente?',
	'ossn:user:delete:exception' => 'Você tem certeza que deseja excluir o usuário?',

	//access
	'title:access:1' => 'Privado',
	'title:access:2' => 'Público',
	'title:access:3' => 'Só Amigos',

	'upload:file:error:ini_size' => 'O arquivo que você tentou enviar é muito grande.',
	'upload:file:error:form_size' => 'O arquivo que você tentou enviar é muito grande..',
	'upload:file:error:partial' => 'O envio do arquivo não foi concluído.',
	'upload:file:error:no_file' => 'Nenhum arquivo foi selecionado.',
	'upload:file:error:no_tmp_dir' => 'Não é possível salvar o arquivo enviado.',
	'upload:file:error:cant_write' => 'Não é possível salvar o arquivo enviado.',
	'upload:file:error:extension' => 'Não é possível salvar o arquivo enviado.',
	'upload:file:error:unknown' => 'O envio de arquivo falhou.',

	'ossn:post:size:exceed' => 'A ação solicitada excede o limite de tamanho.',

	'admin:components' => 'Componentes',
	'admin:themes' => 'Temas',
	'admin:com:installer' => 'Instalador de Componentes',
	'admin:theme:installer' => 'Instalador de Temas',
	'admin:cache:settings' => 'Configuração de Cache',
	'admin:add:user' => 'Adição de usuário',
	'admin:user:list' => 'Lista de usuários',
	'admin:edit:user' => 'Editar usuário',
	'admin:login' => 'Entrar',
	'admin:notification:email' => 'Email para notificação do administrador',
	'notification_email' => 'Notificação por email (noreply@upginformatica.com)',
	'owner_email' => 'Email do Administrador (contato@upginformatica.com)',
	'ossn:websitename' => 'Nome do site web',
	'ossn:user:validation:resend' => 'Sua conta não é válida! Você deve validar sua conta antes de iniciar. Outro email de validação foi enviado para seu endereço de correio electrónico.',
	'site:timepassed:text' => '%s atrás',

	// localization of passed time: 16 time elements (even = singular / odd = plural)
	'site:timepassed:data' => 'segundo|segundos|minuto|minutos|hora|horas|dia|dias|semana|semanas|mês|meses|ano|anos|década|décadas',
	'ossn:notification:no:notification' => 'Nada a mostrar',
	'admin:button:enable' => 'Permitir',
	'admin:button:enabled' => 'Permitir',
	'admin:button:disable' => 'Desativar',
	'admin:button:configure' => 'Configurar',
	'admin:button:delete' => 'Excluir',
	'admin:component:author' => 'Autor',
	'admin:component:website' => 'Site web',
	'admin:sidemenu:components' => 'Componentes',
	'admin:sidemenu:themes' => 'Temas',
	'admin:sidemenu:settings' => 'Configuração do site',
	'admin:sidemenu:usermanager' => 'Administrador de usuário',

	'cancel' => 'Cancelar',
	'ossn:language:complete' => 'Completo',
	'ossn:pagination:first' => 'Primeira',
	'ossn:pagination:last' => 'Último',
	'validate' => 'Validar',
	'admin:users:unvalidated' => 'Usuários não validados',
	'admin:user:validated' => 'Usuários validados',
	'admin:user:validate:error' => 'Não é possível validar o usuário.',


	/*Traduções customizadas*/
	'site:about' => 'Sobre',
	'site:terms' => 'Termos de Utilização',
	'site:privacy' => 'Privacidade',
	'write:comment' => 'Escreva um comentário.',
	'post:select:privacy' => 'Quem verá suas publicações',
	'wall:post:container' => 'O que está pensando?',
	'edit:profile' => 'Editar perfil',
	'user:messages' => 'Mensagens',
	'com:ossn:invite:friends' => 'Convidar amigos',
	'add:group' => 'Adicionar grupo',
	'ossn:notifications:ossnpoke:poke' => 'Você recebeu um toque.',
	'no:messages' => 'Não há mensagens.',
	'ossn:search:topbar:search' => 'Buscar pessoas, lugares e coisas' ,
	'ossn:search' => 'Buscar pessoas, lugares e coisas' ,
    'no:albums' => 'Você não possui álbuns',
	'ossn:chat:no:friend:online' => 'Nenhum amigo Online',
	'reposition:cover' => 'Reposicionar capa',
	'save:position' => 'Salvar alterações',
	'update:info' => 'Atualizar informação',
	'change:cover' => 'Trocar capa',
	'friend:requests' => 'Solicitações de Amizade',
	'profile:photos' => 'Fotos de perfil',
	'profile:covers' => 'Fotos de capa',
	'add:album' => 'Adicionar Álbum',
	'photo:albums' => 'Álbuns',
	'change:photo' => 'Trocar foto',
	'comment:comment' => 'Comentar',
	'enter:location' => 'Onde você está?',
	'ad:title' => 'Título',
	'ad:site:url' => 'Url',
	'ad:desc' => 'Desrição',
	'ad:photo' => 'Imagem',
	'ad:title' => 'Título',
	'ad:site:url' => 'URL',
	'ad:clicks' => 'Click recebidos',
	'ad:browse' => 'Ver',
	'ad:created' => 'Anúncio publicado corretamente !',
	'ad:edited' => 'Anúncio editado com êxito !',
	'ad:deleted' => 'Anúncio excluído com êxito !',
	'ossn:wall:friends:posts' => 'Apenas amigos podem ver publicações',
	'ossn:wall:allsite:posts' => 'Todos podem ver minhas publicações',
	'ossn:wall:admin:notice' => '(Entradas em página)',
	'com:ossn:invite:friends:note' => 'Convide seus amigos para participar da Rede, introduza seus endereços de correio eletrônico e uma breve mensagem. Eles receberão um email com  seu convite.',
	'com:ossn:invite:emails:note' => 'Endereços de correios separados por vírgulas (,)',
	'com:ossn:invite:emails:placeholder' => 'contato@upginformatica.com',
	'com:ossn:invite:message' => 'Mensagem',
    'ossn:search:no:result' => 'Não há resultados',
    'result:type' => 'Tipo de resultado',
    'search:groups' => 'Grupos',
    'search:result' => 'Resultado',
    'group:name' => 'Nome do grupo',
    'privacy:group:public' => 'Qualquer pessoa pode entrar',
    'privacy:group:close' => 'Somente pessoas com convite podem entrar',
    'group:added' => 'O grupo foi adicionado com sucesso',
    'about:group' => 'Sobre o grupo',
    'total:members' => 'Membros',
    'member:requests' => 'Solicitações',
    'view:all' => 'Ver todas',
	'sponsored' => 'Anúncios',
    'groups' => 'Grupos',
    'requests'=> 'Solicitações',
    'no:requests' => 'Não há solicitações',
    'members' => 'Membros',
    'messages' => 'Mensagens',
    'post' => 'Publicar',
    'ossn:profile:cover:picture:updated' => 'Sua capa foi atualizada',
    'ossn:profile:picture:updated' => 'Sua foto de perfil foi trocada',
    'group:desc' => 'Descrição do grupo',
    'edit' => 'Editar',
    'message' => 'Enviar mensagem',
    'user:block' => 'Bloquear usuário',
    'poke' => 'Enviar Toque',
    'see:all' => 'Ver tudo',
    'ossn:notifications:friendrequest:confirmbutton' => 'Aceitar',
    'ossn:notifications:friendrequest:denybutton' => 'Recusar',
    'ossn:notification:are:friends' => 'Agora pode interagir com seu amigo',
    'ossn:post:delete' => 'Excluir publicação',
    'ossn:message:between' => 'Mensagem %s',
    'like' => 'Eu curti',
    'ossn:notifications:like:post' => 'Curtiu seu post',
	'ossn:notifications:comments:post' => 'Comentou seu post',
	'ossn:notifications:delete:friend' => 'Amigo excluído',
	'notifications' => 'Notificações',
	'com:ossn:invite' => 'Nonvidar amigo',
	'unlike' => 'Eu não curti',
	'comment:delete' => 'Comentário excluído',
	'add:photos' => 'Adicionar imagens',
	'delete:photo' => 'Excluir foto',
	'photo:select' => 'Selecionar imagem',
	'back:to:album' => 'Voltar para álbum',
	'message:placeholder' => 'Digite sua mensagem aqui',
	'fields:required' => 'Campos necessários',
	'ossnsitepages'=>'Paginas do Site Ossn',
    'com:ossn:invite:already:members'=>'Amigo já convidado',
    'com:ossn:invite:empty:emails' => 'Digite um endereço de email',
    'com:ossn:invite:sent'=>'Email enviado com sucesso',
    'com:ossn:invite:mail:subject' => 'Você foi convidado a fazer parte da Open Source Social Network',
	'com:ossn:invite:mail:message:default' => 'Acesse http://www.ceestacaocrianca.hol.es e faça seu cadastro',
	'ossn:wall:settings:saved' => 'Configurações salvas',
    'people:like:this' => 'Pessoas que curtiram',
    'post:create:error'=>'Não foi possível publicar o post. Você precisa digitar algum texto',
	'send'=> 'Enviar',



	/*
	 * List of ISO 639-1 language codes
	 * http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
	 */
	"aa" => "Afar",
	"ab" => "Abkhazian",
	"af" => "Afrikaans",
	"am" => "Amharic",
	"ar" => "Arabic",
	"as" => "Assamese",
	"ay" => "Aymara",
	"az" => "Azerbaijani",
	"ba" => "Bashkir",
	"be" => "Byelorussian",
	"bg" => "Bulgarian",
	"bh" => "Bihari",
	"bi" => "Bislama",
	"bn" => "Bengali; Bangla",
	"bo" => "Tibetan",
	"br" => "Breton",
	"ca" => "Catalan",
	"co" => "Corsican",
	"cs" => "Czech",
	"cy" => "Welsh",
	"da" => "Danish",
	"de" => "German",
	"dz" => "Bhutani",
	"el" => "Greek",
	"en" => "English",
	"eo" => "Esperanto",
	"es" => "Español",
	"et" => "Estonian",
	"eu" => "Basque",
	"fa" => "Persian",
	"fi" => "Finnish",
	"fj" => "Fiji",
	"fo" => "Faeroese",
	"fr" => "French",
	"fy" => "Frisian",
	"ga" => "Irish",
	"gd" => "Scots / Gaelic",
	"gl" => "Galician",
	"gn" => "Guarani",
	"gu" => "Gujarati",
	"he" => "Hebrew",
	"ha" => "Hausa",
	"hi" => "Hindi",
	"hr" => "Croatian",
	"hu" => "Hungarian",
	"hy" => "Armenian",
	"ia" => "Interlingua",
	"id" => "Indonesian",
	"ie" => "Interlingue",
	"ik" => "Inupiak",
	"is" => "Icelandic",
	"it" => "Italian",
	"iu" => "Inuktitut",
	"iw" => "Hebrew (obsolete)",
	"ja" => "Japanese",
	"ji" => "Yiddish (obsolete)",
	"jw" => "Javanese",
	"ka" => "Georgian",
	"kk" => "Kazakh",
	"kl" => "Greenlandic",
	"km" => "Cambodian",
	"kn" => "Kannada",
	"ko" => "Korean",
	"ks" => "Kashmiri",
	"ku" => "Kurdish",
	"ky" => "Kirghiz",
	"la" => "Latin",
	"ln" => "Lingala",
	"lo" => "Laothian",
	"lt" => "Lithuanian",
	"lv" => "Latvian/Lettish",
	"mg" => "Malagasy",
	"mi" => "Maori",
	"mk" => "Macedonian",
	"ml" => "Malayalam",
	"mn" => "Mongolian",
	"mo" => "Moldavian",
	"mr" => "Marathi",
	"ms" => "Malay",
	"mt" => "Maltese",
	"my" => "Burmese",
	"na" => "Nauru",
	"ne" => "Nepali",
	"nl" => "Dutch",
	"no" => "Norwegian",
	"oc" => "Occitan",
	"om" => "(Afan) Oromo",
	"or" => "Oriya",
	"pa" => "Punjabi",
	"pl" => "Polish",
	"ps" => "Pashto / Pushto",
	"pt" => "Português Brasileiro",
	"qu" => "Quechua",
	"rm" => "Rhaeto-Romance",
	"rn" => "Kirundi",
	"ro" => "Romanian",
	"ru" => "Russian",
	"rw" => "Kinyarwanda",
	"sa" => "Sanskrit",
	"sd" => "Sindhi",
	"sg" => "Sangro",
	"sh" => "Serbo-Croatian",
	"si" => "Singhalese",
	"sk" => "Slovak",
	"sl" => "Slovenian",
	"sm" => "Samoan",
	"sn" => "Shona",
	"so" => "Somali",
	"sq" => "Albanian",
	"sr" => "Serbian",
	"ss" => "Siswati",
	"st" => "Sesotho",
	"su" => "Sundanese",
	"sv" => "Swedish",
	"sw" => "Swahili",
	"ta" => "Tamil",
	"te" => "Tegulu",
	"tg" => "Tajik",
	"th" => "Thai",
	"ti" => "Tigrinya",
	"tk" => "Turkmen",
	"tl" => "Tagalog",
	"tn" => "Setswana",
	"to" => "Tonga",
	"tr" => "Turkish",
	"ts" => "Tsonga",
	"tt" => "Tatar",
	"tw" => "Twi",
	"ug" => "Uigur",
	"uk" => "Ukrainian",
	"ur" => "Urdu",
	"uz" => "Uzbek",
	"vi" => "Vietnamese",
	"vo" => "Volapuk",
	"wo" => "Wolof",
	"xh" => "Xhosa",
	"yi" => "Yiddish",
	"yo" => "Yoruba",
	"za" => "Zuang",
	"zh" => "Chinese",
	"zu" => "Zulu"
);
ossn_register_languages('pt', $pt);
